/*
  WELCOME TO THE AVAILABILITY BAR COMPONENT
  In here we create a Vertical bar alligned to the left of the parent component
  NOTE: the main component must have a position relative state
  This bar changes color depending on the capacity and booked props
*/
<template>
    <div class="availability-bar" :class="color"></div>
</template>

<script>
export default {
    name: 'AvailabilityBar',
    props: {
        capacity: {
            type: Number,
            required: true
        },
        booked: {
            type: Number,
            required: true
        }
    },
    computed: {
        // in here generate a color class depending of the percentage generated by the booked and capacity props
        color() {
            let percentage = (this.booked * 100) / this.capacity  
            if (percentage <= 20 ) {
                return 'green'
            }
            else if (20 < percentage && percentage <= 90 ) {
                return 'yellow'
            }
            else {
                return 'red'
            }
        }
    }
}
</script>

<style lang="scss" scoped>
@import '@/styles/generic.scss';
 .availability-bar{
        width: 20px;
        height: 100%;

        position: absolute;
        left: 0;
        top: 0;
        
        // green yellow and red color classes are dynamically generated by the color computed property
        &.green{
            background-color: palette(availability, high);
        }
        &.yellow{
            background-color: palette(availability, medium);
        }
        &.red{
            background-color: palette(availability, low);
        }
    }
</style>